title: Studio Legale - Studio Legale Kuehnel

description: >
  Italia: Avv. Elke Kuehnel, Via Camperio 3, 20900 Monza (MB) |  
  Tel: +39.039.6829148, Fax: +39.039.9142269 |  
  Germania: Kanzlei Kuehnel&Engels, Rudolf-Walther-Str. 1, 63584 Gruendau |  
  Tel: +49.(0)6051.48140, Mail: info@studiolegalekuehnel.com

remote_theme: poole/lanyon@v1.1.0

plugins:
  - jekyll-remote-theme

nav_sort: case_insensitive
color_scheme: light
